name: Build and Package

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - '**'

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest] 
        java-version: [17]

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up JDK
      uses: actions/setup-java@v4
      with:
        java-version: ${{ matrix.java-version }}
        distribution: 'adopt'

    - name: Build with Maven
      run: mvn package

    - name: Upload Artifact
      if: success()
      uses: actions/upload-artifact@v4
      with:
        name: GitWave_${{ matrix.os }}_${{ runner.arch }}
        path: target/GitWave.zip
